# deployment
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: iris-web
  name: iris-worker-deployment
  labels:
    app: iris-worker
    site: iris
spec:
  replicas: 1
  selector:
    matchLabels:
      app: iris-worker
  template:
    metadata:
      labels:
        app: iris-worker
    spec:
      containers:
      - name: iris-worker
        image: iriswebapp_app:v2.2.2
        command: ['./wait-for-iriswebapp.sh', 'iris-app-service:8000', './iris-entrypoint.sh', 'iris-worker'] 
        env:
          - name: POSTGRES_USER
            valueFrom:
              secretKeyRef:
                name: iris-app-secrets
                key: POSTGRES_USER
          - name: POSTGRES_PASSWORD
            valueFrom:
              secretKeyRef:
                name: iris-app-secrets
                key: POSTGRES_PASSWORD
          - name: POSTGRES_ADMIN_USER
            valueFrom:
              secretKeyRef:
                name: iris-app-secrets
                key: POSTGRES_ADMIN_USER
          - name: POSTGRES_ADMIN_PASSWORD
            valueFrom:
              secretKeyRef:
                name: iris-app-secrets
                key: POSTGRES_ADMIN_PASSWORD
          - name: POSTGRES_PORT
            valueFrom:
              secretKeyRef:
                name: iris-app-secrets
                key: POSTGRES_PORT
          - name: IRIS_SECRET_KEY
            valueFrom:
              secretKeyRef:
                name: iris-app-secrets
                key: IRIS_SECRET_KEY
          - name: IRIS_SECURITY_PASSWORD_SALT
            valueFrom:
              secretKeyRef:
                name: iris-app-secrets
                key: IRIS_SECURITY_PASSWORD_SALT

          - name: POSTGRES_SERVER
            valueFrom:
              configMapKeyRef:
                name: worker-data
                key: POSTGRES_SERVER
          - name: CELERY_BROKER
            valueFrom:
              configMapKeyRef:
                name: worker-data
                key: CELERY_BROKER
          - name: IRIS_WORKER
            valueFrom:
              configMapKeyRef:
                name: worker-data
                key: IRIS_WORKER
        volumeMounts:
        - name: iris-pcv
          mountPath: /home/iris/downloads
          subPath: downloads
        - name: iris-pcv
          mountPath: /home/iris/user_templates
          subPath: user_templates
        - name: iris-pcv
          mountPath: /home/iris/server_data
          subPath: server_data
      volumes:
      - name: iris-pcv
        persistentVolumeClaim:
          claimName: iris-psql-claim
