apiVersion: v1
kind: Secret
metadata:
  name: iris-app-secrets
  namespace: iris-web
  labels:
    site: iris
type: Opaque
data:
  POSTGRES_USER: cmFwdG9y
  POSTGRES_PASSWORD: YWRtaW4=
  POSTGRES_ADMIN_USER: cmFwdG9y
  POSTGRES_ADMIN_PASSWORD: YWRtaW4=
  POSTGRES_PORT: NTQzMg==
  IRIS_SECRET_KEY: QVZlcnlTdXBlclNlY3JldEtleS1Tb05vdFRoaXNPbmU=
  IRIS_SECURITY_PASSWORD_SALT: QVJhbmRvbVNhbHQtTm90VGhpc09uZUVpdGhlcg==
